// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chats": {
            "get": {
                "description": "get all chats",
                "tags": [
                    "Chat"
                ],
                "summary": "Chat",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "Message"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "get all chats",
                "tags": [
                    "Chat"
                ],
                "summary": "Chat",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "Message"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/chats/:id": {
            "delete": {
                "description": "get all chats",
                "tags": [
                    "Chat"
                ],
                "summary": "Chat",
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "init websocket broadcasr",
                "tags": [
                    "LiveChat"
                ],
                "summary": "LiveChat",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "Message"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
